App\Form\Model\TagFilterModel:
  properties:
    on:
      - NotBlank: ~
      - Optional:
        - Sequentially:
          - Type: { type: integer }
          - Positive: ~
    pg:
      - NotBlank: ~
      - Optional:
        - Sequentially:
          - Type: { type: integer }
          - Positive: ~